In [1]:
import FinalProject as fp

In [2]:
#reload (fp)

In [2]:
d = fp.DigitRecognition()

Class Initialized


In [3]:
d.LoadDataSet()

Loading mydata/train-images-idx3-ubyte.mnist
Loading mydata/train-labels-idx1-ubyte.mnist
Loading mydata/t10k-images-idx3-ubyte.mnist
Loading mydata/t10k-labels-idx1-ubyte.mnist


In [5]:
#d.ResetModelVariables()

In [4]:
d.create_nn_model()

In [5]:
d.DisplayModelVariables()

[u'W1', u'B1', u'W2', u'B2', u'W3', u'B3', u'W4', u'B4', u'W5', u'B5']

In [9]:
#TRAINING
d.StartTraining(100)

Variables: [u'W1', u'B1', u'W2', u'B2', u'W3', u'B3', u'W4', u'B4', u'W5', u'B5', u'beta1_power', u'beta2_power', u'W1/Adam', u'W1/Adam_1', u'B1/Adam', u'B1/Adam_1', u'W2/Adam', u'W2/Adam_1', u'B2/Adam', u'B2/Adam_1', u'W3/Adam', u'W3/Adam_1', u'B3/Adam', u'B3/Adam_1', u'W4/Adam', u'W4/Adam_1', u'B4/Adam', u'B4/Adam_1', u'W5/Adam', u'W5/Adam_1', u'B5/Adam', u'B5/Adam_1']
0: accuracy:0.06 loss: 249.855 (lr:0.003)
0: ********* epoch 1 ********* test accuracy:0.0645 test loss: 245.243
20: accuracy:0.87 loss: 65.9533 (lr:0.00297114451787)
40: accuracy:0.88 loss: 37.7268 (lr:0.00294257615259)
60: accuracy:0.94 loss: 16.9184 (lr:0.00291429204729)
80: accuracy:0.94 loss: 19.6467 (lr:0.00288628937354)
100: accuracy:0.94 loss: 19.7537 (lr:0.00285856533105)
100: ********* epoch 1 ********* test accuracy:0.9369 test loss: 22.1591


In [5]:
saver = fp.tf.train.Saver()

In [6]:
([v.op.name for v in fp.tf.all_variables()])

[u'W1', u'B1', u'W2', u'B2', u'W3', u'B3', u'W4', u'B4', u'W5', u'B5']

In [56]:
#tf.reset_default_graph() 

In [10]:
with fp.tf.Session() as sess:
    saver.restore(sess,'checkpoints/myModel')
    print sess.run(fp.W1)

[[[[-0.02115657  0.03520161  0.00819837 -0.06452606 -0.08437051  0.09891038]]

  [[-0.04156521 -0.01284502 -0.0598077  -0.11632653 -0.10910994  0.13673028]]

  [[-0.00955042 -0.01346881  0.14497247  0.03063136 -0.00107064  0.10663541]]

  [[ 0.0988976  -0.06364649  0.17184064 -0.1633279  -0.19966076 -0.09478993]]

  [[-0.1115704   0.23911633 -0.01627478 -0.07697462 -0.09897471 -0.12114099]]

  [[-0.02541327  0.10410011  0.0502089  -0.02212091  0.05662746 -0.15746063]]]


 [[[-0.02011288  0.09439781  0.00215353 -0.01581034  0.03313693  0.01982349]]

  [[-0.11597306 -0.01333761  0.11710901  0.03772597 -0.19236463  0.05214006]]

  [[ 0.0059426  -0.02085669  0.08543755 -0.11999221  0.04045146  0.00153505]]

  [[-0.02997066  0.02812305  0.19359016 -0.07964794 -0.04151425  0.03387735]]

  [[ 0.02781948  0.0283102   0.14876242  0.03916391 -0.12736864 -0.16509809]]

  [[ 0.00361586  0.03528702  0.03894098  0.0431024   0.01007389 -0.19362843]]]


 [[[ 0.12080944  0.1369565   0.08795745 -0.09466

In [11]:
dTest = fp.DigitRecognition()

Class Initialized


In [12]:
dTest.create_nn_model()

In [14]:
saver = dTest.tf.train.Saver()

AttributeError: DigitRecognition instance has no attribute 'train'

In [2]:
range(1,20)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [14]:
range(1000 // 20 + 1)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [8]:
#saver.export_meta_graph()

In [21]:
sess.run({X: mnist.test.images, Y_: mnist.test.labels, pkeep: 1.0})

NameError: name 'mnist' is not defined

In [17]:
correct_prediction = tf.equal(tf.argmax(Y, 1), tf.argmax(Y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

NameError: name 'Y' is not defined